### PR TITLE
Use Gemfile to manage development dependencies

### PR DESCRIPTION
**Pull request by olleolleolle**
### 🤔 What's changed?

Move from a set of pinned dependencies in the gemspec, to a set of Gemfile `gem` directives.

### ⚡️ What's your motivation? 

I'd like for there to be fewer PRs to maintain this repo.

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
- [ ] My change requires a change to the documentation.
- [ ] Users should know about my change

----

### CODE REVIEW

**Comment by mvz** [comment]
> I'd like for there to be fewer PRs to maintain this repo.

How exactly does this help with that? There don't seem to be that many PRs in this repo anyway.

**Comment by olleolleolle** [comment]
By nit having any more version pins than we absolutely need, and not keeping a lockfile around, there's little to do for a PR-making bot. That was my thinking.

**Comment by mvz** [comment]
Oh I see. I didn't notice versions were unpinned in addition to the dependencies being moved. That makes sense.

Regarding the move from gemspec to Gemfile, what motivated that part?

(As an aside, is this repo even maintained? I'm not doing anything here, and those dependencies look way outdated to begin with.)

**Comment by olleolleolle** [comment]
For me, it was that I got GitHub notifications about the PRs for changes to deps. So, I tried to work us away from that. 

Other than that, I've never used this repo for anything.

**Comment by mvz** [comment]
> For me, it was that I got GitHub notifications about the PRs for changes to deps. So, I tried to work us away from that.

Oh I see there are several. I'm not watching this repo so didn't get any notifications.

**Comment by mvz** [comment]
How about merging #9, #11 and #10 first to bring things up-to-date?

**Comment by olleolleolle** [comment]
@mvz Good idea. Done!

**Review by mvz — APPROVED** [review]

**Pull request merged**
